spring:
  datasource:
    url: jdbc:mysql://localhost:3306/Cafe?createDatabaseIfNotExist=true
    username: root
    password: rootFor1917
    driver-class-name: com.mysql.cj.jdbc.Driver
    
  jpa:
      hibernate:
        naming:
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
